name: beta semantic release
on:
  workflow_dispatch:

jobs:
  beta-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          branches: |
            [
              'dummy',
              {
                name: 'master',
                prerelease: true
              },
            ]
          extra_plugins: |
            @semantic-release/changelog@^5.0.1
            @semantic-release/git@9.0.0
            @semantic-release/exec
            conventional-changelog-conventionalcommits@^4.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Do something when a new release published
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
          echo ${{ steps.semantic.outputs.new_release_major_version }}
          echo ${{ steps.semantic.outputs.new_release_minor_version }}
          echo ${{ steps.semantic.outputs.new_release_patch_version }}
